import Head from 'next/head'
//import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Nav from "../components/Nav"
import Items from '../components/Items'
import Customer from '../components/Customer'
export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Just Desserts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Nav></Nav>
      </main>
      <div>
        <Items></Items>
             
       
        <Customer></Customer>
      
      </div>
    </div>

  )
}
